# Generated by Django 5.2.3 on 2025-07-01 23:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.base')),
                ('nameImage', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='TablePromotion',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.base')),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Value Min is 0')])),
                ('juros', models.BooleanField(default=False)),
            ],
            bases=('app.base',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.base')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0, message='Value Min is R$: 00.00')])),
                ('description', models.CharField(max_length=255)),
                ('textAdd', models.TextField(blank=True, max_length=255, null=True)),
                ('urlProduct', models.URLField(unique=True)),
                ('promotion', models.BooleanField(default=False)),
                ('avaliacoes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('img', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.imageproduct')),
                ('tablePromotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablepromotion')),
            ],
            bases=('app.base',),
        ),
    ]
