# Generated by Django 5.1.7 on 2025-03-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_localmodel_thememodel_remove_modeluser_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='localmodel',
            name='slug',
        ),
    ]
