# Generated by Django 5.1.2 on 2024-10-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakenews',
            name='local',
            field=models.CharField(default='Desconhecido', max_length=50),
        ),
        migrations.AlterField(
            model_name='fakenews',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
