# Generated by Django 4.2.10 on 2024-10-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fakenews_local_alter_fakenews_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sugestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugestions', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('themes_default', models.CharField(choices=[('A', 'Arnold'), ('B', 'Beraldo')], max_length=30, unique=True)),
            ],
        ),
    ]
